
modLoader = "javafml"
loaderVersion = "*"

license = "${mod_license}"
issueTrackerURL = "${mod_github}/issues"

[[mixins]]
config = "${mod_id}.mixins.json"
[[mixins]]
config = "${mod_id}-common.mixins.json"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "icon.png"
authors = "${mod_authors}"
credits = "${mod_credits}"
description = '''${mod_description}'''
modUrl = "${mod_homepage}"
itemIcon="minecraft:endstone" #catalogue icon

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "REQUIRED"
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "REQUIRED"
versionRange = "[${minecraft_min_version},${minecraft_max_version})"
ordering = "NONE"
side = "BOTH"
